server.servlet.context-path=/EPSGuest/
# Use JNDI datasource provided by WildFly
spring.datasource.jndi-name=java:jboss/datasources/OracleDS

#spring.datasource.bv1to1.jndi-name=jdbc/CRIS 
#spring.datasource.irmms.jndi-name=jdbc/IRMMS
spring.datasource.irmms.jndi-name=jdbc/CRIS
#spring.datasource.imms.jndi-name=jdbc/IMMS
spring.banner.location=classpath:/bannername.txt
debug = true
logging.level.root=WARN
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=ERROR
#logging.level.org.hibernate.SQL=ERROR 
logging.level.org.hibernate.type=ERROR
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=true
server.error.whitelabel.enabled=false
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.main.allow-bean-definition-overriding=true
spring.jpa.open-in-view=false

spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.com.ireps=DEBUG

logging.level.org.springframework.web: DEBUG
       