imms.functionCode.admin=4001
imms.userDepot.functionCode.stockVerfication=4034
imms.userDepot.functionCode.rejectionHandling=4033
imms.userDepot.functionCode.adviceNoteDS-8=4032
imms.userDepot.functionCode.adjMemoPinkSlip=4031
imms.userDepot.functionCode.gatePass=4030
imms.userDepot.functionCode.CRN=4029
imms.userDepot.functionCode.GenRequisition=4028

